<div class="post single-item dev-mockup">

	<!-- 
	CUSTOM MARKUP HERE. 

	NOTICE THAT THE POST/SINGLE-ITEM CONTAINER IS NEEDED AND DEFINE THE OUTER CONTAINER OF A SINGLE POST BOX.
	WHILE YOU CAN ADD CUSTOM CLASSES TO THE SINGLE-ITEM CONTAINER IN DEV MODE SINGLE-ITEM CONTAINER CLASSES ARE NOT CONTROLLABLE IN FINAL THEME. 
	ONLY CLASS YOU CAN RELY ON FOR CONTAINER IS THE SINGLE-ITEM CLASS.
	SO DO NOT CREATE STYLING THAT IS DEPENDENT ON CUSTOM CLASSES PUT ON THE SINGLE-ITEM CONTAINER.

	DO NOTICE THAT THE FINAL THEME CAN ONLY HAVE ONE BOX VARIATION FOR A STANDARD POST. 
	SO ALTHOUGH YOU CAN PLAY AROUND WITH DIFFERENT MOCKUP VARIATIONS IN DEV MODE ONLY ONE VARIATION CAN BE USED IN FINAL THEME.
	-->

</div>

